// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAbB0GIw6EJvjOJOHQz-CVWlJHsnE-anU',
    appId: '1:950866677017:web:8f8b4b7d78019a9a120988',
    messagingSenderId: '950866677017',
    projectId: 'letters-and-numbers-24',
    authDomain: 'letters-and-numbers-24.firebaseapp.com',
    storageBucket: 'letters-and-numbers-24.appspot.com',
    measurementId: 'G-KG6SRMQNWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzQYJ2QI_wetagEtcqMf7jokOpmdQaqHc',
    appId: '1:950866677017:android:64bf2465e510153d120988',
    messagingSenderId: '950866677017',
    projectId: 'letters-and-numbers-24',
    storageBucket: 'letters-and-numbers-24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeaCpOT0xGQ1Yt1tPZGZtgPm3dAMHWcqc',
    appId: '1:950866677017:ios:a8cf255e65a81080120988',
    messagingSenderId: '950866677017',
    projectId: 'letters-and-numbers-24',
    storageBucket: 'letters-and-numbers-24.appspot.com',
    iosBundleId: 'com.codesphere.lettersnumber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeaCpOT0xGQ1Yt1tPZGZtgPm3dAMHWcqc',
    appId: '1:950866677017:ios:fa30cbd8eb048a83120988',
    messagingSenderId: '950866677017',
    projectId: 'letters-and-numbers-24',
    storageBucket: 'letters-and-numbers-24.appspot.com',
    iosBundleId: 'com.codesphere.lettersnumber.RunnerTests',
  );
}
